<?php

return [
    "Groningen" => "01",
    "Friesland" => "02",
    "Noord-Holland Noord" => "03",
    "Drenthe" => "04",
    "Regio Zwolle" => "05",
    "Flevoland" => "06",
    "Zaanstreek/Waterland" => "07",
    "Zuid-Kennemerland" => "08",
    "Twente" => "09",
    "Groot Amsterdam" => "10",
    "Veluwe Stedendriehoek" => "11",
    "Gooi en Vechtstreek" => "12",
    "Holland Rijnland" => "13",
    "Midden-Utrecht" => "14",
    "Amersfoort" => "15",
    "FoodValley" => "16",
    "Achterhoek" => "17",
    "Zuid-Holland Centraal" => "18",
    "Midden Holland" => "19",
    "Haaglanden" => "20",
    "Midden-Gelderland" => "21",
    "Rijnmond" => "22",
    "Rivierenland" => "23",
    "Gorinchem" => "24",
    "Rijk van Nijmegen" => "25",
    "Drechtsteden" => "26",
    "Noordoost-Brabant" => "27",
    "West-Brabant" => "28",
    "Zeeland" => "29",
    "Midden-Brabant" => "30",
    "Noord-Limburg" => "31",
    "Helmond-De Peel" => "32",
    "Zuidoost-Brabant" => "33",
    "Midden-Limburg" => "34",
    "Zuid-Limburg" => "35",
];
