<?php

return [
    "DD01" => "Geen uitkering",
    "DD02" => "Participatiewet (Bijstand, IOAW, IOAZ)",
    "DD03" => "Wajong",
    "DD04" => "WAO, WIA, WAZ",
    "DD05" => "WW, IOW",
    "DD06" => "Ondernemer met personeel",
    "DD07" => "Zelfstandige ondernemer (ZZP)",
    "DD08" => "Met werkloosheid bedreigd",
    "ED01" => "Jongeren tot 27 jaar",
    "ED02" => "50-plussers",
    "ED03" => "(Vermoedelijk) Verstandelijke beperking (IQ 50-85)",
    "ED04" => "(Vermoedelijk) Arbeidsbeperkten",
    "ED05" => "Statushouders",
    "ED06" => "Migranten",
    "ED07" => "(Ex) Ondernemers",
    "ED08" => "Dak- en thuislozen",
    "ED09" => "Laaggeletterden en analfabeten",
    "ED10" => "ZZP-er",
    "ED11" => "Met werkloosheid bedreigd",
    "ED12" => "Banenafspraak (doelgroepregister)",
    "ED13" => "NUG-ers",
    "ED14" => "Medewerkers",
];
